### ISSUE TITLE
Hue temperature range

### ISSUE THREAD

**Issue by claytonjn** [KristopherKubicki/smartapp-circadian-daylight#13]
"The Hue bulbs are only capable of producing a true color spectrum from 2700K to 6000K. The Hue Pro application indicates the range is a little wider on each side, but I stuck with the Philips documentation"

Out of curiosity, where did you see that information? In the API they specify **hue supports color temperatures from 2000K (warm) to 6500K (cold) with great white light** (http://www.developers.meethue.com/documentation/core-concepts)

I'm wondering if the API got updated?

Regardless, they specify that "the light will go to the closest value it can produce if the specified color temperature is outside of the achievable range" so I think best practice would be to send whatever color temperature value would be optimal for the circadian rhythm, and let the device adapt to the nearest color it is capable of producing.

Personally, I would like to see this SmartApp setting colors based on this graph, with times relative to local sunrise and sunset: http://sigmaluminous.com/the-circadian-rhythm-and-color-temperature/

I can work on this if you think that it's a valuable update to the project.

**Comment by KristopherKubicki** [comment]
I believe the API was updated from the previous restriction to the new one.  Thank you for this update.
